config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  resources :users, only: [:show]
  resources :foods, only: [ :index, :new, :create, :destroy ]
  resources :recipes, except: [:edit] do
    resources :foods_recipe, only: [:new, :create, :destroy]
  end
    
  get "/public_recipes", to: "recipes#public_recipes"
  get "/general_shopping_lists", to: "general_shopping_lists#index"
  # get "/recipes/:id/add-ingredients", to: "recipes#ingredients", as: "add_ingredients"

  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :foods_recipes
  has_many :recipes, through: :foods_recipes

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/models/foods_recipe.rb
class FoodsRecipe < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :foods_recipes
  has_many :foods, through: :foods_recipes

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    if resource.errors.empty?
      super(resource)
    else
      # Redirect to the registration page with errors displayed
      new_user_registration_path
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @food = Food.new
  end

  def index
    @foods = Food.includes(:user).where(user_id: current_user)
  end

  def create
    @food = Food.new(new_food)
    @food.user = current_user

    if @food.save
      flash[:notice] = 'New food added!'
      redirect_to foods_path
    else
      flash[:alert] = "Error! #{@food.errors.full_messages.join(', ')}"
      redirect_to new_food_path
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy!
    flash[:notice] = 'Food deleted successfully!'
    redirect_to foods_path
  end

  private

  def new_food
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/foods_recipe_controller.rb
class FoodsRecipeController < ApplicationController
  def new
    @foods_recipe = FoodsRecipe.new
    @foods = Food.where(user_id: current_user)
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @foods_recipe = FoodsRecipe.new(food_recipe_params)
    @recipe = Recipe.find(params[:recipe_id])
    @foods_recipe.recipe = @recipe

    if @foods_recipe.save
      flash[:notice] = 'Ingredient added successfully!'
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = 'Error adding ingredient.'
      redirect_to recipes_path
    end
  end

  def destroy
    @foods_recipe = FoodsRecipe.find(params[:id])
    if @foods_recipe
      @recipe = @foods_recipe.recipe
      @foods_recipe.destroy
      flash[:notice] = 'Ingredient deleted successfully!'
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = 'Unable to delete ingredient!'
    end
  end

  private

  def food_recipe_params
    params.require(:foods_recipe).permit(:food_id, :quantity)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  def index
    # 1. Get all the recipes of the current user
    users_recipes = Recipe.where(user_id: current_user)

    # 2. Figure out the food items that need to be bought
    food_required_for_all_recipes = Hash.new(0)

    users_recipes.each do |recipe|
      recipe.foods.each do |food|
        food_required_for_all_recipes[food] += recipe.foods_recipes.find_by(food_id: food.id).quantity
      end
    end

    # 3. Compute items that need to be bought,
    # For each food, we want the food name, quantity, and total price
    @foods_to_buy = []

    food_required_for_all_recipes.each do |current_food, required_quantity|
      available_quantity = current_food.quantity

      next unless required_quantity > available_quantity

      @foods_to_buy << {
        food_name: current_food.name,
        quantity_to_buy: "#{required_quantity - available_quantity} #{current_food.measurement_unit}",
        total_price: (required_quantity - available_quantity) * current_food.price
      }
    end

    @grand_total = @foods_to_buy.sum { |food| food[:total_price] }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipe = Recipe.new
  end

  def index
    @recipes = Recipe.where(user_id: current_user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user_has_access = @recipe.user_id == current_user.id || @recipe.public
    @foods_recipe = @recipe.foods_recipes.includes(:food)
  end

  def create
    @recipe = Recipe.new(new_recipe)
    @recipe.user = current_user

    if @recipe.save
      flash[:notice] = 'New recipe added!'
      redirect_to recipes_path
    else
      flash[:alert] = "Error! #{@recipe.errors.full_messages.join(', ')}"
      redirect_to new_recipe_path
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to recipe_path(@recipe), notice: 'Recipe updated successfully!'
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!
    flash[:notice] = 'Recipe deleted successfully!'
    redirect_to recipes_path
  end

  def public_recipes
    @recipes = Recipe.includes(:user).where(public: true).order(created_at: :desc)

    @total_prices = {}

    @recipes.each do |recipe|
      total = 0
      recipe.foods_recipes.each do |foods_recipe|
        total += foods_recipe.quantity * foods_recipe.food.price
      end

      @total_prices[recipe.name] = total
    end
  end

  private

  def new_recipe
    params.require(:recipe).permit(:name, :cooking_time, :preparation_time, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/foods_recipe_helper.rb
module FoodsRecipeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<section>
  <h1>Food list</h1>
  <%= link_to 'Add New Food', new_food_path, class: 'btn' %>
  <%= render 'partials/food_table' %>
</section>

app/views/foods/new.html.erb
<section>
  <h1>Add new food</h1>
  <%= form_with model: @food, url: foods_path do |f| %>
    <div>
      <%= f.label :name%>:
      <%= f.text_field :name%>
    </div>
    <div>
      <%= f.label :measurement_unit%>:
      <%= f.text_field :measurement_unit%>
    </div>
    <div>
      <%= f.label :price%>:
      <%= f.number_field :price, min: 1 %>
    </div>
    <div>
      <%= f.label :quantity%>:
      <%= f.number_field :quantity, min: 1 %>
    </div>
    <%= f.submit 'Add food', class: 'btn' %>
  <%end%>
</section>

app/views/foods_recipe/new.html.erb
<section>
<h2>Add Ingredients to <%= @recipe.name %> recipe</h2>

<%= form_with model: [@recipe, @foods_recipe], url: recipe_foods_recipe_index_path(@recipe) do |f| %>
  <div>
    <%= f.label :food_id, 'Select Food' %>
    <%= f.select(:food_id, @foods.map { |food| [food.name, food.id] }, { prompt: 'Select Food' }) if @foods.present? %>
  </div>
  <div>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, min: 1 %>
  </div>
  <%= f.submit 'Add Ingredient' %>
<% end %></section>

app/views/general_shopping_lists/index.html.erb
<section>
  <h1>Shopping list</h1>
  <section>
    <div class="shopping-summary">
      <p>
        Amount of food items to buy <b><%= @foods_to_buy.length %></b>
      </p>
      <p>
        Total value of food needed <b>$ <%= @grand_total %></b>
      </p>
    </div>
    <%= render 'partials/shopping_list_table' %>
  </section>
</section>

app/views/home/index.html.erb
<main>
  <section>
    <h1>Welcome to the recepi app!</h1>
    <p>Explore a world of culinary delights with our recipe app. From mouthwatering dishes to quick snacks, discover a diverse collection of recipes that suit your taste and skill level.</p>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorGroupProj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <% unless controller_path.start_with?('devise/') %>
        <%= render 'partials/navbar' %>
      <% end %>
    </header>
    
    <!-- Devise uses notice and alert messages -->
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/publicRecipes.html.erb
<section>
  <h1>Public Recipes</h1>
  <% @recipes.each do |recipe| %>
  <section>
    <div>
      <%= link_to recipe_path(recipe) do %>
      <h3><%= recipe.name %> </h3>
      <% end %>
      <p>By: <%= recipe.user.name %> </p>
    </div>
    <div>
      <p>Total food items: 4 </p>
      <p>Total price: $203 </p>
    </div>
  </section>
  <% end %>
</section>

app/views/partials/_food_table.html.erb
<div>
  <div id="table">
    <table class="generic-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Measurement Unit</th>
          <th>Quantity</th>
          <th>Unit Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.quantity %></td>
            <td>$<%= food.price %></td>
            <td>
              <%= form_with model: food, url: food_path(food), method: :delete do |f| %>
                <%= f.submit 'Delete', class: 'btn btn-danger' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if @foods.empty? %>
    <p>You have no food</p>
    <script>
      document.getElementById('table').style.display = 'none';
    </script>
  <% end %>
</div>

app/views/partials/_navbar.html.erb
<nav class='main-nav'>
  <ul class='nav-list'>
    <li class='logo'>
      <%= link_to root_path do%>
        <%= image_tag(asset_path('logo.png'), alt: 'Recipe App logo') %>
      <% end %>
    </li>
    <% if user_signed_in? %>
      <div>
        <li><%= link_to 'My Foods', foods_path %></li>
        <li><%= link_to 'My Recipes', recipes_path %></li>
        <li><%= link_to 'Public Recipes', public_recipes_path %></li>
        <li><%= link_to 'Shopping List', general_shopping_lists_path %></li>
      </div>
      <li><%= button_to 'Sign out', destroy_user_session_path, class: 'btn btn-danger', method: :delete %></li>         
    <% else %>
      <li><%= button_to 'Sign In', new_user_session_path, class: 'btn' %></li>
    <% end %>
  </ul>
</nav>

app/views/partials/_recipe_table.html.erb
<table class="generic-table">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <% if current_user.id == @recipe.user_id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @foods_recipe.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %></td>
        <td>$<%= recipe_food.food.price  * recipe_food.quantity %></td>
        <% if current_user.id == @recipe.user_id %>
          <td>
            <%= form_with model: recipe_food, url: recipe_foods_recipe_path(@recipe, recipe_food), method: :delete do |f| %>
              <%= f.submit 'Delete' %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_shopping_list_table.html.erb
<div>
  <div id="table">
    <table class="generic-table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @foods_to_buy.each do |food| %>
          <tr>
            <td><%= food[:food_name] %></td>
            <td><%= food[:quantity_to_buy] %></td>
            <td><%= food[:total_price] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if @foods_to_buy.empty? %>
    <p>You have all the food you need for your recipes!</p>
    <script>
      document.getElementById('table').style.display = 'none';
    </script>
  <% end %>
</div>

app/views/recipes/index.html.erb
<section>
  <h1>Recipe List</h1>
  <%= link_to 'Add Recipe', new_recipe_path, class: 'btn' %>
  <% user_has_recipes = false %>
  <div class="recipe-card-wrapper">
    <% @recipes.each do |recipe| %>
      <% if recipe.user == current_user %>
        <% user_has_recipes = true %>
        <div class="recipe-card">
          <%= link_to recipe_path(recipe) do %>
          <h2><%= recipe.name %> </h2>
          <% end %>
          <%= form_with model: recipe, url: recipe_path(recipe), method: :delete do |f| %>
            <%= f.submit 'Remove', class: 'btn btn-danger' %>
          <% end %>
          <p><%= recipe.description %> </p>
        </div>
      <% end %>
    <% end %>
  </div>
  <% unless user_has_recipes %>
    <p>You have no recipes.</p>
  <% end %>
</section>

app/views/recipes/new.html.erb
<section>
  <h1>Add Recipe</h1>
    <%= form_with model: @recipe, url: recipes_path do |f| %>
    <div>
      <%= f.label :name%>:
      <%= f.text_field :name%>
    </div>
    <div>
      <%= f.label :preparation_time%>:
      <%= f.text_field :preparation_time%>
    </div>
    <div>
      <%= f.label :cooking_time%>:
      <%= f.text_field :cooking_time%>
    </div>
    <div>
      <%= f.label :description%>:
      <%= f.text_area :description%>
    </div>
    <%= f.submit 'Add recipe', class: 'btn' %>
  <%end%>
</section>

app/views/recipes/public_recipes.html.erb
<section>
  <h1>Public Recipes</h1>
  <div class="recipe-card-wrapper">
    <% @recipes.each do |recipe| %>
      <div class="recipe-card">
        <%= link_to recipe_path(recipe) do %>
        <h2><%= recipe.name %> </h2>
        <% end %>
        <p>By: <b><%= recipe.user.name %></b> </p>
        <p>Total food items: <b><%= recipe.foods_recipes.length %></b> </p>
        <p>Total price: <b><%= @total_prices[recipe.name] %></b> </p>
      </div>
    <% end %>
  </div>
</section>

app/views/recipes/show.html.erb
<section>
  <h1><%= @recipe.name %> </h1>
  <% if @user_has_access %>
    <div>
      <p><b>Preparation time:</b> <%= @recipe.preparation_time %> </p>
      <p><b>cooking time:</b> <%= @recipe.cooking_time %> </p>
      <p><b>Steps:</b></p>
      <p><%= @recipe.description %> </p>

      <% if current_user.id == @recipe.user_id %>
      <div class="btns-wrapper">
        <%= form_with(model: @recipe, url: recipe_path(@recipe), method: :patch, remote: true) do |f| %>
          <%= f.hidden_field :public, value: !@recipe.public, disabled: true %>
          <%if @recipe.public? %>
            <%= f.submit 'Switch to private', class: 'btn btn-danger' %>
          <% else %>
            <%= f.submit 'Switch to public', class: 'btn' %>
          <% end %>
        <% end %>
        <% end %>

        <%= link_to 'Generate shopping list', general_shopping_lists_path, class: 'btn btn-secondary' %>
        <% if current_user.id == @recipe.user_id %>
          <%= link_to 'Add Ingredients', new_recipe_foods_recipe_path(@recipe), class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
    <%= render 'partials/recipe_table' %>
  <% else %>
    <section>You do not have access to this recipi because the owner has not made it public.</section>
  <% end %>
</section>

app/views/users/show.html.erb
<section>
  <h1>Users#show</h1>
  <div>
    <p><%= @user.name %></p>
  </div>
</section>